#!/usr/bin/env python
import sys

import matplotlib
matplotlib.use('Agg') # prevent use of a display

from analysis.Pipeline import Pipeline
from analysis.PipelineModules import BASE, KD_SAMPLING
print('arguments:'+str(sys.argv))
p = Pipeline(sys.argv[1],modules=KD_SAMPLING)
p.execute()